[versions]
shadow = "8.1.8"
nmcp = "0.0.9"

[libraries]
shadow = { group = "io.github.goooler.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
nmcp = { group = "com.gradleup.nmcp", name = "nmcp", version.ref = "nmcp" }