name: FoliaSchedulerTestPlugin
author: Bram
description: A simple test plugin to test the FoliaScheduler library.
website: https://github.com/Bram1903/FoliaScheduler
main: com.deathmotion.testfoliascheduler.TestPlugin
version: ${version}
api-version: '1.13'
folia-supported: true
load: POSTWORLD